"""State-tracking probe tasks for linear-attention layers.

Two tasks from the Chomsky-hierarchy / state-tracking literature, following the
DeltaProduct paper's Appendix C.2 protocol (arXiv:2502.10297): train on short
sequences, test on much longer ones, and measure length generalization.

Both tasks are *word problems in a group*: the model must maintain a running
group element across the sequence. That is exactly the capability a product of
R Householder factors is claimed to buy over a single factor, which is why the
effect here is near-binary rather than a fraction of a nat.

- ``parity``   -- the group Z/2. Solvable by a single-factor delta rule.
- ``s3_words`` / ``s4_words`` / ``s5_words`` -- the symmetric groups S3, S4, S5. These
  form an *arity ladder*: Thm 4 / Table 1 of the paper states that one layer with R
  Householder factors represents permutations of at most ``R + 1`` elements, so at
  fixed R difficulty should rise monotonically S3 -> S4 -> S5, and R must grow to
  cover S5 at fixed depth.
- ``mod_arith`` -- modular arithmetic without brackets over Z/5 with ops ``{+, -, *}``.
  A structurally different family (not permutation composition), so a finding on the
  Sn ladder can be cross-checked against a task with different algebraic structure.
"""

from __future__ import annotations

from functools import partial

import torch

# Symmetric groups as permutations of n elements, each generated by a transposition
# and an n-cycle (the standard 2-element generating set for Sn).
S3_GENERATORS = (
    (1, 0, 2),  # swap first two
    (1, 2, 0),  # 3-cycle
)
S4_GENERATORS = (
    (1, 0, 2, 3),  # swap first two
    (1, 2, 3, 0),  # 4-cycle
)
S5_GENERATORS = (
    (1, 0, 2, 3, 4),  # swap first two
    (1, 2, 3, 4, 0),  # 5-cycle
)

# A5, the alternating group on 5 elements: order 60, non-solvable, and generated by two EVEN
# permutations (a 3-cycle and a 5-cycle). Both facts are the point.
#
# A5 is the experiment that separates two competing explanations of why S5 is hard, which every
# group above is equally consistent with:
#
#   - the "solvability" account: S5 is hard because it is non-solvable.
#   - the "arity" account: S5 is hard because a delta-product layer with R factors can only
#     realize permutations reachable from R Householder terms, independent of solvability.
#
# DeltaProduct (arXiv:2502.10297v7, section 5) settles it for the per-head-gated case, verbatim:
# "for S3 achieving reliable performance beyond sequence lengths of 128 requires n_h = 2, while
# S5 needs n_h = 4. Unexpectedly, S4 and A5 can extrapolate robustly using only n_h = 2 despite
# the theorem suggesting 3 and 4, respectively." A5 is non-solvable yet behaves like solvable S4,
# because both are isomorphic to subgroups of SO(3) -- A5 to the rotation group of the
# dodecahedron. So solvability is NOT the discriminator there.
#
# Whether that carries over to a *per-channel* gate is unmeasured, and this entry exists to
# measure it. A per-channel gate has K independent decay channels rather than one per head, so
# it is not obvious the same arity bound applies.
#
# Note both generators being even is what makes A5 the clean control: it means no single input
# token asks the layer for an odd permutation (det = -1), which is the specific thing strict
# beta in (0,1) cannot represent -- every erase factor has det = 1-beta > 0. S5's transposition
# generator does ask for one. So A5 vs S5 also isolates the parity obstruction from group order.
A5_GENERATORS = (
    (1, 2, 0, 3, 4),  # 3-cycle (even)
    (1, 2, 3, 4, 0),  # 5-cycle (even)
)

# Modular arithmetic without brackets: Z/p with p = 5 and three binary operations.
MOD_ARITH_P = 5
MOD_ARITH_OPS = ("+", "-", "*")


def _compose(perm: tuple[int, ...], other: tuple[int, ...]) -> tuple[int, ...]:
    """Return the composition ``other after perm``."""
    return tuple(other[perm[i]] for i in range(len(perm)))


def _enumerate_group(generators: tuple[tuple[int, ...], ...], n: int) -> list[tuple[int, ...]]:
    """Breadth-first closure of ``generators`` under composition."""
    identity = tuple(range(n))
    seen = {identity: 0}
    frontier = [identity]
    while frontier:
        nxt = []
        for element in frontier:
            for gen in generators:
                candidate = _compose(element, gen)
                if candidate not in seen:
                    seen[candidate] = len(seen)
                    nxt.append(candidate)
        frontier = nxt
    return sorted(seen, key=lambda p: seen[p])


def make_parity(batch: int, length: int, generator: torch.Generator) -> tuple[torch.Tensor, torch.Tensor]:
    """Running parity of a bit string.

    :returns: ``(inputs, targets)``, both ``[batch, length]`` int64. Vocabulary is
        ``{0, 1}``; the target at position ``t`` is the parity of ``inputs[:, :t+1]``.
    """
    inputs = torch.randint(0, 2, (batch, length), generator=generator)
    targets = inputs.cumsum(dim=-1) % 2
    return inputs, targets


def make_group_words(
    batch: int,
    length: int,
    generator: torch.Generator,
    generators: tuple[tuple[int, ...], ...] = S5_GENERATORS,
    n: int = 5,
) -> tuple[torch.Tensor, torch.Tensor]:
    """Running product of group generators (default: S5 word problem).

    Each input token selects a generator; the target at position ``t`` is the index
    of the accumulated product of the first ``t+1`` generators.

    :returns: ``(inputs, targets)``, both ``[batch, length]`` int64. Input vocabulary
        is ``len(generators)``; target vocabulary is the group order (120 for S5).
    """
    elements = _enumerate_group(generators, n)
    index_of = {element: i for i, element in enumerate(elements)}

    inputs = torch.randint(0, len(generators), (batch, length), generator=generator)
    targets = torch.empty_like(inputs)
    running = [tuple(range(n))] * batch
    for t in range(length):
        for b in range(batch):
            running[b] = _compose(running[b], generators[inputs[b, t].item()])
            targets[b, t] = index_of[running[b]]
    return inputs, targets


def _mod_arith_step_table(p: int = MOD_ARITH_P) -> torch.Tensor:
    """Build the per-token transition table for modular arithmetic without brackets.

    Token ``s`` encodes the pair ``(op, operand)`` as ``op * p + operand``, so the input
    vocabulary is ``len(MOD_ARITH_OPS) * p``. Entry ``[s, a]`` is the accumulator value
    after applying step ``s`` to accumulator ``a``.

    :param p: modulus of the ring Z/p.
    :returns: ``[len(MOD_ARITH_OPS) * p, p]`` int64 lookup table.
    """
    acc = torch.arange(p).view(1, p)
    operand = torch.arange(p).view(p, 1)
    per_op = [
        (acc + operand) % p,
        (acc - operand) % p,
        (acc * operand) % p,
    ]
    return torch.cat(per_op, dim=0).to(torch.int64)


def make_mod_arith(
    batch: int,
    length: int,
    generator: torch.Generator,
    p: int = MOD_ARITH_P,
) -> tuple[torch.Tensor, torch.Tensor]:
    """Modular arithmetic without brackets over Z/p (default p = 5, ops ``{+, -, *}``).

    Each input token is a single symbol encoding one ``(op, operand)`` step as
    ``op * p + operand``; the accumulator starts at 0 and the target at position ``t`` is
    its value *after* applying steps ``0..t``, mirroring ``make_parity``'s running target.

    Vectorized: each step is lifted to its ``[p, p]`` transition table and the running
    composition is obtained with a Hillis-Steele inclusive scan, so the cost is
    ``O(log length)`` torch ops rather than a Python loop over ``batch * length``.

    :param batch: number of sequences.
    :param length: sequence length.
    :param generator: torch RNG used to draw the tokens.
    :param p: modulus of the ring Z/p.
    :returns: ``(inputs, targets)``, both ``[batch, length]`` int64. Input vocabulary is
        ``len(MOD_ARITH_OPS) * p`` (15 by default); target vocabulary is ``p``.
    """
    in_vocab = len(MOD_ARITH_OPS) * p
    inputs = torch.randint(0, in_vocab, (batch, length), generator=generator)

    # prefix[b, t] is the composed map Z/p -> Z/p for steps 0..t of sequence b.
    prefix = _mod_arith_step_table(p)[inputs]  # [batch, length, p]
    stride = 1
    while stride < length:
        # out[b, t, a] = prefix[b, t + stride, prefix[b, t, a]] -- later map applied second.
        composed = torch.gather(prefix[:, stride:], dim=2, index=prefix[:, : length - stride])
        prefix = torch.cat((prefix[:, :stride], composed), dim=1)
        stride *= 2

    targets = prefix[:, :, 0].contiguous()  # accumulator starts at 0
    return inputs, targets



# --- MQAR (multi-query associative recall) -----------------------------------------------------
# Disjoint vocabulary ranges: 0 is the separator, then keys, then values, then distractors.
MQAR_NUM_KEYS = 32
MQAR_NUM_VALUES = 32
MQAR_NUM_DISTRACTORS = 32
# Cap on pairs per sequence. Holding this fixed while sequence length grows is what turns the
# length sweep into a pure RETENTION-DISTANCE test rather than a capacity test. Must be
# <= MQAR_NUM_KEYS for keys to be sampled without replacement.
MQAR_MAX_PAIRS = 8
MQAR_SEP = 0
MQAR_KEY_BASE = 1
MQAR_VALUE_BASE = MQAR_KEY_BASE + MQAR_NUM_KEYS
MQAR_DISTRACTOR_BASE = MQAR_VALUE_BASE + MQAR_NUM_VALUES
MQAR_VOCAB = MQAR_DISTRACTOR_BASE + MQAR_NUM_DISTRACTORS
MQAR_IGNORE = -100
# Minimum distractor span. Below this the task is a lookup, not a recall test.
MQAR_MIN_FILLER = 16


def mqar_num_pairs(length: int, max_pairs: int = MQAR_MAX_PAIRS) -> int:
    """Number of key-value pairs to use at a given sequence length.

    Grows with length until ``max_pairs``, then stays flat so that additional length becomes
    distractor filler (retention distance) rather than extra memory load (capacity).

    :param length: Sequence length.
    :param max_pairs: Cap on the pair count.
    :returns: Number of pairs, at least 1.
    """
    return max(1, min(max_pairs, (length - 1) // 3))


def mqar_vocab(n_keys: int, n_values: int, n_distractors: int) -> int:
    """Total vocabulary size for an MQAR variant (separator + keys + values + distractors)."""
    return 1 + n_keys + n_values + n_distractors


def make_mqar(
    batch: int,
    length: int,
    generator: torch.Generator,
    max_pairs: int = MQAR_MAX_PAIRS,
    n_keys: int = MQAR_NUM_KEYS,
    n_values: int = MQAR_NUM_VALUES,
    n_distractors: int = MQAR_NUM_DISTRACTORS,
) -> tuple[torch.Tensor, torch.Tensor]:
    """Multi-query associative recall.

    Layout (causal, answers strictly after all pairs)::

        k1 v1 k2 v2 ... kD vD  <distractors ...>  SEP  q1 q2 ... qD

    The target at each query position is the value paired with that key; every other position is
    :data:`MQAR_IGNORE` (``-100``, ``cross_entropy``'s default ``ignore_index``). Keys, values and
    distractors occupy disjoint vocabulary ranges, and keys are drawn **without replacement**
    within a sequence so each has exactly one correct value.

    Difficulty is governed by ``max_pairs`` relative to the model's recurrent state capacity, and
    by ``n_values`` (which sets chance accuracy at ``1 / n_values``). Holding ``max_pairs`` fixed
    while sequence length grows turns a length sweep into a pure retention-distance test rather
    than a capacity test.

    :param batch: Batch size.
    :param length: Sequence length; must leave room for ``2D + 1 + D`` tokens.
    :param generator: RNG for reproducibility.
    :param max_pairs: Cap on pairs per sequence. Must be ``<= n_keys``.
    :param n_keys: Size of the key range.
    :param n_values: Size of the value range; chance accuracy is ``1 / n_values``.
    :param n_distractors: Size of the filler range.
    :returns: ``(inputs, targets)``, both ``[batch, length]`` int64.
    """
    assert max_pairs <= n_keys, f"max_pairs={max_pairs} exceeds n_keys={n_keys}"
    D = mqar_num_pairs(length, max_pairs)
    # Need 2D pair tokens + 1 separator + D queries, PLUS at least MQAR_MIN_FILLER distractors.
    # Without a distractor span the pairs run straight into the queries and the task degenerates
    # from associative *recall* into a local lookup -- nothing has to be retained across anything.
    # That silently made the highest-load variant the EASIEST one (measured: mqar_d128 at L=256
    # got 0 filler and scored 18x chance while lower-load variants sat at chance).
    if length < 3 * D + 1 + MQAR_MIN_FILLER:
        raise ValueError(
            f"mqar needs length >= {3 * D + 1 + MQAR_MIN_FILLER} for D={D} "
            f"(2D pairs + sep + D queries + {MQAR_MIN_FILLER} filler), got {length}"
        )

    key_base = MQAR_KEY_BASE
    value_base = key_base + n_keys
    distractor_base = value_base + n_values

    inputs = torch.empty(batch, length, dtype=torch.int64)
    targets = torch.full((batch, length), MQAR_IGNORE, dtype=torch.int64)

    key_perm = torch.argsort(torch.rand(batch, n_keys, generator=generator), dim=1)
    keys = key_perm[:, :D] + key_base
    values = torch.randint(0, n_values, (batch, D), generator=generator) + value_base

    inputs[:, 0 : 2 * D : 2] = keys
    inputs[:, 1 : 2 * D : 2] = values

    sep_at = length - D - 1
    n_filler = sep_at - 2 * D
    if n_filler > 0:
        inputs[:, 2 * D : sep_at] = (
            torch.randint(0, n_distractors, (batch, n_filler), generator=generator)
            + distractor_base
        )
    inputs[:, sep_at] = MQAR_SEP

    # Fresh random query order, so answer position carries no information about which key is asked.
    order = torch.argsort(torch.rand(batch, D, generator=generator), dim=1)
    inputs[:, sep_at + 1 :] = torch.gather(keys, 1, order)
    targets[:, sep_at + 1 :] = torch.gather(values, 1, order)
    return inputs, targets



TASKS = {
    "parity": {"fn": make_parity, "in_vocab": 2, "out_vocab": 2},
    "s3_words": {
        "fn": partial(make_group_words, generators=S3_GENERATORS, n=3),
        "in_vocab": len(S3_GENERATORS),
        "out_vocab": 6,
    },
    "s4_words": {
        "fn": partial(make_group_words, generators=S4_GENERATORS, n=4),
        "in_vocab": len(S4_GENERATORS),
        "out_vocab": 24,
    },
    "s5_words": {"fn": make_group_words, "in_vocab": len(S5_GENERATORS), "out_vocab": 120},
    # A5: non-solvable like S5, but order 60 and both generators even. See A5_GENERATORS.
    "a5_words": {
        "fn": partial(make_group_words, generators=A5_GENERATORS, n=5),
        "in_vocab": len(A5_GENERATORS),
        "out_vocab": 60,
    },
    "mod_arith": {
        "fn": make_mod_arith,
        "in_vocab": len(MOD_ARITH_OPS) * MOD_ARITH_P,
        "out_vocab": MOD_ARITH_P,
    },
    "mqar": {
        "fn": make_mqar,
        "in_vocab": MQAR_VOCAB,
        "out_vocab": MQAR_VOCAB,
    },
    # Graded MQAR variants. The base "mqar" (D<=8, vocab 32) was measured at 100% accuracy out to
    # length 512 -- at ceiling, hence useless for comparing arms. These raise the memory load
    # relative to the recurrent state so that accuracy lands strictly between chance and ceiling.
    # LOAD LADDER, fixed vocabulary. The graded d16/d32/d64/d128 variants above vary the pair
    # count AND the vocabulary together, so a difference between them cannot be attributed to
    # either (measured: D<=8/vocab97 -> 99.6%, D<=16/vocab385 -> chance; two changes, one cliff).
    # These hold keys/values/distractors at 128 each -- so chance is 1/128 = 0.78% throughout --
    # and vary ONLY the number of pairs the recurrent state must hold.
    #
    # Expected binding constraint: the delta rule writes k(x)v outer products into a K=64 state,
    # so associations interfere once the keys can no longer stay near-orthogonal. That predicts a
    # transition somewhere below D ~ K, which is what this ladder is built to locate.
    "mqar_p8": {
        "fn": partial(make_mqar, max_pairs=8, n_keys=128, n_values=128, n_distractors=128),
        "in_vocab": mqar_vocab(128, 128, 128),
        "out_vocab": mqar_vocab(128, 128, 128),
    },
    "mqar_p16": {
        "fn": partial(make_mqar, max_pairs=16, n_keys=128, n_values=128, n_distractors=128),
        "in_vocab": mqar_vocab(128, 128, 128),
        "out_vocab": mqar_vocab(128, 128, 128),
    },
    "mqar_p24": {
        "fn": partial(make_mqar, max_pairs=24, n_keys=128, n_values=128, n_distractors=128),
        "in_vocab": mqar_vocab(128, 128, 128),
        "out_vocab": mqar_vocab(128, 128, 128),
    },
    "mqar_p32": {
        "fn": partial(make_mqar, max_pairs=32, n_keys=128, n_values=128, n_distractors=128),
        "in_vocab": mqar_vocab(128, 128, 128),
        "out_vocab": mqar_vocab(128, 128, 128),
    },
    # GRADED LADDER, vocabulary varies WITH the pair count: n_* = 8 * max_pairs, capped at 512
    # (d128 would want 1024). This is the ladder the comment at the top of this block warns is
    # confounded -- it is retained as a diagnostic, not as a controlled contrast.
    #
    # There is deliberately no "mqar_d16" rung. Under the 8x rule its vocabulary would be 128,
    # which makes it byte-identical to "mqar_p16" above -- verified: same inputs and same targets
    # at a fixed seed. The two ladders genuinely intersect at D=16, so the rung is not missing,
    # it is spelled "mqar_p16". A "mqar_d16" entry did exist and was an exact duplicate of
    # "mqar_p16"; it was removed rather than given a made-up vocabulary, because any vocabulary
    # other than 128 would break the ladder's own 8x rule and no other value was ever intended.
    "mqar_d32": {
        "fn": partial(make_mqar, max_pairs=32, n_keys=256, n_values=256, n_distractors=256),
        "in_vocab": mqar_vocab(256, 256, 256),
        "out_vocab": mqar_vocab(256, 256, 256),
    },
    "mqar_d64": {
        "fn": partial(make_mqar, max_pairs=64, n_keys=512, n_values=512, n_distractors=512),
        "in_vocab": mqar_vocab(512, 512, 512),
        "out_vocab": mqar_vocab(512, 512, 512),
    },
    "mqar_d128": {
        "fn": partial(make_mqar, max_pairs=128, n_keys=512, n_values=512, n_distractors=512),
        "in_vocab": mqar_vocab(512, 512, 512),
        "out_vocab": mqar_vocab(512, 512, 512),
    },
}


def _self_check() -> None:
    """Validate group orders, target ranges, and the vectorized ``mod_arith`` scan."""
    sizes = {
        "S3": len(_enumerate_group(S3_GENERATORS, 3)),
        "S4": len(_enumerate_group(S4_GENERATORS, 4)),
        "S5": len(_enumerate_group(S5_GENERATORS, 5)),
    }
    assert sizes == {"S3": 6, "S4": 24, "S5": 120}, sizes
    print(f"BFS closure sizes: {sizes}")

    for name, spec in TASKS.items():
        gen = torch.Generator().manual_seed(0)
        # Length 512 satisfies every task's minimum: the running-product tasks accept any
        # length, and the MQAR variants need 3D + 1 + MQAR_MIN_FILLER (up to 401 at D=128).
        inputs, targets = spec["fn"](8, 512, gen)
        assert inputs.shape == targets.shape == (8, 512), (name, inputs.shape, targets.shape)
        assert inputs.dtype == targets.dtype == torch.int64, (name, inputs.dtype, targets.dtype)
        assert int(inputs.min()) >= 0 and int(inputs.max()) < spec["in_vocab"], name
        # Ignore-indexed positions (-100) are excluded: they are deliberately outside the
        # vocabulary and are dropped by both cross_entropy and the accuracy computation.
        scored = targets[targets != MQAR_IGNORE]
        assert scored.numel() > 0, f"{name}: every position is ignored"
        assert int(scored.min()) >= 0 and int(scored.max()) < spec["out_vocab"], (
            name,
            int(scored.max()),
            spec["out_vocab"],
        )
        print(
            f"{name:>9}: in_vocab={spec['in_vocab']:>3} out_vocab={spec['out_vocab']:>3} "
            f"targets in [{int(targets.min())}, {int(targets.max())}]"
        )

    # Cross-check the scan against a naive sequential reference.
    table = _mod_arith_step_table(MOD_ARITH_P)
    gen = torch.Generator().manual_seed(1)
    inputs, targets = make_mod_arith(4, 37, gen)
    reference = torch.zeros_like(targets)
    acc = torch.zeros(inputs.shape[0], dtype=torch.int64)
    for t in range(inputs.shape[1]):
        acc = table[inputs[:, t], acc]
        reference[:, t] = acc
    assert torch.equal(targets, reference), "mod_arith scan disagrees with sequential reference"
    print("mod_arith scan matches sequential reference")

    # Hand-checkable sample rows.
    gen = torch.Generator().manual_seed(0)
    s3_in, s3_tg = TASKS["s3_words"]["fn"](1, 8, gen)
    s3_elements = _enumerate_group(S3_GENERATORS, 3)
    print(f"s3_words inputs : {s3_in[0].tolist()}")
    print(f"s3_words targets: {s3_tg[0].tolist()}")
    print(f"s3_words perms  : {[s3_elements[i] for i in s3_tg[0].tolist()]}")

    gen = torch.Generator().manual_seed(0)
    ma_in, ma_tg = make_mod_arith(1, 8, gen)
    decoded = [f"{MOD_ARITH_OPS[s // MOD_ARITH_P]}{s % MOD_ARITH_P}" for s in ma_in[0].tolist()]
    print(f"mod_arith inputs : {ma_in[0].tolist()} -> {' '.join(decoded)}")
    print(f"mod_arith targets: {ma_tg[0].tolist()}")


if __name__ == "__main__":
    _self_check()
